# foundry.toml
[profile.default]
fs_permissions = [{ access = "read", path = "./"}]
evm_version = "shanghai"
src = "src"
out = "out"
libs = ["lib"]  # Points to your lib directory where dependencies are stored

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"  # Change this to your actual RPC endpoint URL if needed



