# foundry.toml
[profile.default]
fs_permissions = [{ access = "read", path = "./"}]
evm_version = "shanghai"
src = "src"
out = "out"
libs = ["lib"]  # Points to your lib directory where dependencies are stored

remappings = [
  "@aave-v3-core/=lib/aave-v3-core/",
  "@aave-v3-origin/=lib/aave-v3-origin/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@forge-std/=lib/forge-std/",
  "@ethx/=lib/ethx/",
  "@v3-periphery/=lib/v3-periphery/",
  
  # OpenZeppelin contracts upgradeable
  "@openzeppelin/contracts-upgradeable/=lib/aave-v3-origin/lib/solidity-utils/lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts/=lib/aave-v3-origin/lib/solidity-utils/lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  
  # Other libraries
  "ds-test/=lib/aave-v3-origin/lib/forge-std/lib/ds-test/src/",
  "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
  "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
  "openzeppelin-foundry-upgrades/=lib/ethx/lib/openzeppelin-foundry-upgrades/src/",
  "solidity-stringutils/=lib/ethx/lib/openzeppelin-foundry-upgrades/lib/solidity-stringutils/",
  "solidity-utils/=lib/aave-v3-origin/lib/solidity-utils/"
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"  # Change this to your actual RPC endpoint URL if needed



