name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

steps:
      # Checkout the repository with submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures submodules are fetched
          fetch-depth: 0    # Fetches the full history, avoiding shallow clone issues

# Set up Foundry
      - name: Set up Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.foundry/bin/foundryup
          
      # Install Foundry dependencies
      - name: Install Foundry dependencies
        run: |
          forge install  # Installs dependencies (if any) for Foundry

      # Build the project
      - name: Build project
        run: |
          forge build  # Build the smart contracts using Foundry

      # Optional: Run tests
      - name: Run tests
        run: |
          forge test  # Run the tests (if you have any)
